### ISSUE TITLE
Misleading upstream url

### ISSUE THREAD

**Issue by nikosalonen** [TheBastionBot/BastionBotDevDocs#1]
In the `pulls.md` (https://github.com/TheBastionBot/BastionBotDevDocs/blob/master/docs/contributing/pulls.md#step-1-fork) the guide suggest adding `nodejs` github repo as upstream. 

This can be confusing for someone.

**Comment by k3rn31p4nic** [comment]
@nikosalonen Thanks for pointing that out, would you like to open a PR for the fix?

**Comment by nikosalonen** [comment]
Yeah I'll fix it
